server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

logging.level.com.checkout.payment.gateway=DEBUG

bank.url=http://localhost:8080
bank.connect-timeout=10s
bank.read-timeout=10s

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=never